// Generated by scripts/sync-ui-theme.ps1. Edit assets/ui/design-tokens.json.
#pragma once
#include <cstdint>
namespace dhre::ui {
inline constexpr std::uint32_t kBlack = 789002;
inline constexpr char kBlackHex[] = "#0A0A0C";
inline constexpr std::uint32_t kSurface = 1644054;
inline constexpr char kSurfaceHex[] = "#161619";
inline constexpr std::uint32_t kSurfaceRaised = 2564642;
inline constexpr char kSurfaceRaisedHex[] = "#222227";
inline constexpr std::uint32_t kSurfaceHover = 3222315;
inline constexpr char kSurfaceHoverHex[] = "#2B2B31";
inline constexpr std::uint32_t kLine = 3814452;
inline constexpr char kLineHex[] = "#34343A";
inline constexpr std::uint32_t kWhite = 16777215;
inline constexpr char kWhiteHex[] = "#FFFFFF";
inline constexpr std::uint32_t kMuted = 13156030;
inline constexpr char kMutedHex[] = "#BEBEC8";
inline constexpr std::uint32_t kPurple = 16403847;
inline constexpr char kPurpleHex[] = "#874DFA";
inline constexpr std::uint32_t kPurpleHover = 16738713;
inline constexpr char kPurpleHoverHex[] = "#9969FF";
inline constexpr std::uint32_t kConnected = 10216287;
inline constexpr char kConnectedHex[] = "#5FE39B";
inline constexpr std::uint32_t kWarning = 6078207;
inline constexpr char kWarningHex[] = "#FFBE5C";
inline constexpr int kHairline = 1;
inline constexpr int kHalfGap = 4;
inline constexpr int kCompactSpace = 8;
inline constexpr int kMediumSpace = 12;
inline constexpr int kSpace = 16;
inline constexpr int kHeaderHeight = 46;
inline constexpr int kHeaderInset = 7;
inline constexpr int kHeaderIconSize = 32;
inline constexpr int kControlHeight = 40;
inline constexpr int kCompactControlHeight = 28;
inline constexpr int kFooterHeight = 40;
inline constexpr int kTitlePixels = 29;
inline constexpr int kBodyPixels = 17;
inline constexpr int kSmallPixels = 15;
inline constexpr int kCreditPixels = 14;
inline constexpr int kRegularWeight = 400;
inline constexpr int kStrongWeight = 700;
inline constexpr wchar_t kTitleFamily[] = L"Quintessential";
inline constexpr char kTitleFamilyName[] = "Quintessential";
inline constexpr wchar_t kBodyFamily[] = L"Montserrat";
inline constexpr char kBodyFamilyName[] = "Montserrat";
}
