[CmdletBinding()]
param([string]$PeerRoot, [switch]$Check)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$theme = Get-Content -LiteralPath (Join-Path $root 'assets/ui/design-tokens.json') -Raw | ConvertFrom-Json
$cpp = [Collections.Generic.List[string]]::new()
$palette = [Collections.Generic.List[string]]::new()
$metrics = [Collections.Generic.List[string]]::new()
$css = [Collections.Generic.List[string]]::new()
$css.Add('/* Generated by scripts/sync-ui-theme.ps1. */')
$css.Add(':root {')
$cpp.Add('// Generated by scripts/sync-ui-theme.ps1. Edit assets/ui/design-tokens.json.')
$cpp.Add('#pragma once')
$cpp.Add('#include <cstdint>')
$cpp.Add('namespace dhre::ui {')
$palette.Add('// Generated by scripts/sync-ui-theme.ps1. Edit assets/ui/design-tokens.json.')
$palette.Add('namespace DhreView.UI;')
$palette.Add('internal static class BrandPalette {')
$metrics.Add('// Generated by scripts/sync-ui-theme.ps1. Logical pixels at 96 DPI; fonts use points.')
$metrics.Add('namespace DhreView.UI;')
$metrics.Add('internal static class BrandMetrics {')
foreach ($property in $theme.colors.PSObject.Properties) {
    $name = $property.Name
    $hex = $property.Value
    $cssName = [regex]::Replace($name, '(?<!^)[A-Z]', '-$0').ToLowerInvariant()
    $css.Add("  --${cssName}: $hex;")
    $r = [Convert]::ToInt32($hex.Substring(1, 2), 16)
    $g = [Convert]::ToInt32($hex.Substring(3, 2), 16)
    $b = [Convert]::ToInt32($hex.Substring(5, 2), 16)
    $cpp.Add("inline constexpr std::uint32_t k$name = $($r -bor ($g -shl 8) -bor ($b -shl 16));")
    $cpp.Add("inline constexpr char k${name}Hex[] = `"$hex`";")
    $palette.Add("    internal static readonly Color $name = Color.FromArgb($r, $g, $b);")
}
foreach ($property in $theme.metrics.PSObject.Properties) {
    $cssName = [regex]::Replace($property.Name, '(?<!^)[A-Z]', '-$0').ToLowerInvariant()
    $unit = if ($property.Name.EndsWith('Weight')) { '' } else { 'px' }
    $css.Add("  --${cssName}: $($property.Value)$unit;")
    $cpp.Add("inline constexpr int k$($property.Name) = $($property.Value);")
    $metrics.Add("    internal const int $($property.Name) = $($property.Value);")
}
foreach ($role in @('Title', 'Body', 'Small', 'Credit')) {
    $metrics.Add("    internal const float ${role}FontSize = ${role}Pixels * 72F / 96F;")
}
foreach ($property in $theme.fonts.PSObject.Properties) {
    $cpp.Add("inline constexpr wchar_t k$($property.Name)Family[] = L`"$($property.Value)`";")
    $cpp.Add("inline constexpr char k$($property.Name)FamilyName[] = `"$($property.Value)`";")
    $metrics.Add("    internal const string $($property.Name)Family = `"$($property.Value)`";")
}
$cpp.Add('}')
$palette.Add('}')
$metrics.Add('}')
$css.Add('}')

function Write-OrCheck([string]$path, [string]$content) {
    $content = $content.Replace("`r`n", "`n").TrimEnd() + "`n"
    if ($Check) {
        if (-not (Test-Path -LiteralPath $path) -or
            [IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $content) {
            throw "UI theme is out of sync: $path. Run scripts/sync-ui-theme.ps1."
        }
    } else {
        [IO.Directory]::CreateDirectory((Split-Path -Parent $path)) | Out-Null
        [IO.File]::WriteAllText($path, $content, [Text.UTF8Encoding]::new($false))
    }
}

$roots = @($root)
if ($PeerRoot) { $roots += [IO.Path]::GetFullPath($PeerRoot) }
foreach ($target in $roots) {
    if (-not (Test-Path -LiteralPath (Join-Path $target 'src'))) { throw "Invalid project: $target" }
    if ($target -ne $root) {
        foreach ($shared in @('assets/ui/design-tokens.json', 'assets/ui/obs_theme.hpp', 'assets/ui/README.md', 'scripts/sync-ui-theme.ps1')) {
            Write-OrCheck (Join-Path $target $shared) ([IO.File]::ReadAllText((Join-Path $root $shared)))
        }
    }
    Write-OrCheck (Join-Path $target 'assets/ui/brand_theme.hpp') ($cpp -join "`n")
    Write-OrCheck (Join-Path $target 'assets/ui/brand-theme.css') ($css -join "`n")
    if (Test-Path -LiteralPath (Join-Path $target 'src/dhreView/UI')) {
        Write-OrCheck (Join-Path $target 'src/dhreView/UI/BrandPalette.cs') ($palette -join "`n")
        Write-OrCheck (Join-Path $target 'src/dhreView/UI/BrandMetrics.cs') ($metrics -join "`n")
    }
}
Write-Output 'UI theme is synchronized.'
